---
- name: Install k8s dependencies
  hosts: all
  become: yes
  roles:
    - role: docker
    - role: docker-cri
    - role: k8s

- name: Initialize k8s cluster
  hosts: masters
  become: yes
  roles:
    - role: k8s_master

- name: Join cluster
  hosts: computes
  become: yes
  roles:
    - role: k8s_workers

