


- name: Copy the calico file.
  copy:
    src: calico.yml
    dest: /calico.yml 

- name: Ensure /etc/cni/net.d directory exists
  ansible.builtin.file:
    path: /etc/cni/net.d
    state: directory
  become: yes

- name: Apply Calico manifest
  command: kubectl apply -f /calico.yml
  environment:
    KUBECONFIG: "/etc/kubernetes/admin.conf"

- name: Wait for master node to be ready
  wait_for:
    host: "{{ ansible_host }}"
    port: 6443
    state: started
